package: tst
packages:
  - packageA
  - packageB
version: 0.0.0
language: kotlin
classified: true
scripts:
  build: |
    go build
    rm -f /c/Users/sderisme/.jpm/jpm.exe
    cp jpm.exe /c/Users/sderisme/.jpm/jpm.exe
dependencies:
  - google com.android.tools.lint:lint:31.13.1 exec
repos:
  - default: https://repo1.maven.org/maven2/
  - google: https://maven.google.com/
