package: tst
packages:
  - packageA
  - packageB
version: 0.0.1
language: kotlin
classified: true
scripts:
  build: jpm build-{{jpm.OS}}
  build-linux: make build -B
  build-darwin: make build -B
  build-windows: go build; rm -f ~/.jpm/jpm.exe; cp jpm.exe ~/.jpm/jpm.exe
dependencies:
  - rsync:1.0.0 exec
  - com.github.lalyos jfiglet:0.0.9 exec
repos:
  - default: https://repo1.maven.org/maven2/
  - google: https://maven.google.com/
languages:
  - kotlin
  - java
  - scala
  - groovy
  - clojure
paths: []
