package: tst
packages:
  - packageA
  - packageB
version: 0.0.0
language: kotlin
classified: true
scripts:
  print: jfiglet ...args@
  build: |
    go build
    rm -f /c/Users/sderisme/.jpm/jpm.exe
    cp jpm.exe /c/Users/sderisme/.jpm/jpm.exe
dependencies:
  - rsync:1.0.0 exec
  - com.github.lalyos jfiglet:0.0.9 exec
repos:
  - default: https://repo1.maven.org/maven2/
  - google: https://maven.google.com/
paths: []
