package: tst
classified: true
packages: ["packageA", "packageB"]
scripts:
  build: |
    go build
    rm -f /c/Users/sderisme/go/bin/jpm.exe
    cp jpm.exe /c/Users/sderisme/go/bin/jpm.exe
dependencies:
  - local localdepA
  - local ../
  - local ../localdepB
  - local localdepA/localdepC
