package: tst
packages:
  - packageA
  - packageB
version: 0.0.0
language: kotlin
classified: true
scripts:
  print: |
    case "args@[0]" in
      -h)
        echo "Usage: jpm print [message]"
        ;;
      -normal)
        echo "args@[last]"
        ;;
      -fancy)
        jfiglet "args@[last]"
        ;;
      *)
        echo "Usage: jpm print [message]"
        ;;
    esac
  build: |
    go build
    rm -f /c/Users/sderisme/.jpm/jpm.exe
    cp jpm.exe /c/Users/sderisme/.jpm/jpm.exe
dependencies:
  - rsync:1.0.0 exec
  - com.github.lalyos jfiglet:0.0.9 exec
repos:
  - default: https://repo1.maven.org/maven2/
  - google: https://maven.google.com/
paths: []
languages: [kotlin, java,scala, groovy, clojure]
