#!/bin/sh
curdir="$(pwd)"
max_traverse=20
traverse_count=0
found_package_yml=0
while [ $traverse_count -lt $max_traverse ]; do
	if [ -f "$curdir/package.yml" ]; then
		cd "$curdir"
		found_package_yml=1
		break
	fi
	parentdir="$(dirname "$curdir")"
	if [ "$parentdir" = "$curdir" ]; then
		break
	fi
	curdir="$parentdir"
	traverse_count=$((traverse_count+1))
done

if [ $found_package_yml -eq 0 ]; then
	echo "Error: package.yml not found"
	exit 1
fi
if [ $# -eq 0 ]; then
	echo "Usage: jpx [-d] <command> [args...]"
	echo "            -d: run command in detached mode"
	echo "available commands :"
	for file in "$curdir/jpm_dependencies/execs/"*; do
		if [ -x "$file" ] && [ -f "$file" ]; then
			echo " > $(basename "$file")"
		fi
	done
else
	export PATH="$curdir/jpm_dependencies/execs:$PATH"
	if [ "$1" = "-d" ]; then
		shift
		"$@" > /dev/null 2>&1 &
		echo "Started in detached mode: $*"
	else
		"$@"
	fi
fi