#!/bin/sh
curdir="$(pwd)"
max_traverse=10
traverse_count=0
found_package_yml=0

if [ $# -eq 0 ]; then
	echo "Add exec dependencies to your package.yml to make it available to jpx"
	echo "available commands :"
	for file in "$curdir/jpm_dependencies/execs/"*; do
		if [ -x "$file" ] && [ -f "$file" ]; then
			echo " > $(basename "$file")"
		fi
	done
else
	while [ $traverse_count -lt $max_traverse ]; do
		if [ -f "$curdir/package.yml" ]; then
			cd "$curdir"
			found_package_yml=1
			break
		fi
		parentdir="$(dirname "$curdir")"
		if [ "$parentdir" = "$curdir" ]; then
			break
		fi
		curdir="$parentdir"
		traverse_count=$((traverse_count+1))
	done

	if [ $found_package_yml -eq 0 ]; then
		echo "Error: package.yml not found"
		exit 1
	fi
	export PATH="$curdir/jpm_dependencies/execs:$PATH"
	"$@"
fi